export default {
  "login": "rmusayevr",
  "id": 89644850,
  "node_id": "MDQ6VXNlcjg5NjQ0ODUw",
  "avatar_url": "https://avatars.githubusercontent.com/u/89644850?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/rmusayevr",
  "html_url": "https://github.com/rmusayevr",
  "followers_url": "https://api.github.com/users/rmusayevr/followers",
  "following_url": "https://api.github.com/users/rmusayevr/following{/other_user}",
  "gists_url": "https://api.github.com/users/rmusayevr/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/rmusayevr/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/rmusayevr/subscriptions",
  "organizations_url": "https://api.github.com/users/rmusayevr/orgs",
  "repos_url": "https://api.github.com/users/rmusayevr/repos",
  "events_url": "https://api.github.com/users/rmusayevr/events{/privacy}",
  "received_events_url": "https://api.github.com/users/rmusayevr/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Rashad Musayev",
  "company": "Codelandia",
  "blog": "",
  "location": "Baku, Azerbaijan",
  "email": null,
  "hireable": null,
  "bio": "Full-Stack Developer (Django)\r\n",
  "twitter_username": null,
  "public_repos": 37,
  "public_gists": 1,
  "followers": 21,
  "following": 18,
  "created_at": "2021-08-27T12:53:26Z",
  "updated_at": "2023-09-19T18:45:49Z"
};